### ISSUE TITLE
Remote Application Event Issue.

### ISSUE THREAD

**Issue by Tapsprofile** [spring-cloud/spring-cloud-bus#206]
Issue on the Spring Cloud Bus when using the Event Functionality.
I have one microservice and created a listener.
Another microservice which sends the data to the rabbit mq.
Need a fix for the below message.
```
2019-08-29 11:44:47.139  INFO 7488 --- [  restartedMain] com.hm.ivu.sd.procengine.SdEngine        : Started SdEngine in 11.795 seconds (JVM running for 13.04)
2019-08-29 11:45:18.615 ERROR 7488 --- [mKv4fNUPCYX0A-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Could not resolve type id 'BootEvent' as a subtype of [simple type, class org.springframework.cloud.bus.event.RemoteApplicationEvent]: known type ids = [AckRemoteApplicationEvent, EnvironmentChangeRemoteApplicationEvent, RefreshRemoteApplicationEvent, UnknownRemoteApplicationEvent]
 at [Source: (byte[])"{"type":"BootEvent","timestamp":1567059315124,"originService":"application:7388:09a19c44b336e9aacedc353de3a16b82","destinationService":"**","id":"cb5fa79e-9ce9-4037-a1a6-358bb41fb589","value":"startup bootEvent from Controller published"}"; line: 1, column: 9]; nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'BootEvent' as a subtype of [simple type, class org.springframework.cloud.bus.event.RemoteApplicationEvent]: known type ids = [AckRemoteApplicationEvent, EnvironmentChangeRemoteApplicationEvent, RefreshRemoteApplicationEvent, UnknownRemoteApplicationEvent]
 at [Source: (byte[])"{"type":"BootEvent","timestamp":1567059315124,"originService":"application:7388:09a19c44b336e9aacedc353de3a16b82","destinationService":"**","id":"cb5fa79e-9ce9-4037-a1a6-358bb41fb589","value":"startup bootEvent from Controller published"}"; line: 1, column: 9], failedMessage=GenericMessage [payload=byte[238], headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, deliveryAttempt=3, amqp_consumerQueue=springCloudBus.anonymous.nqDvY1YbRmKv4fNUPCYX0A, amqp_redelivered=false, amqp_receivedRoutingKey=springCloudBus, amqp_timestamp=Thu Aug 29 11:45:15 IST 2019, amqp_messageId=a2a19ae9-5ccb-ec1e-c4fd-e4bbf1f5c220, id=4e379c8f-fbc7-75f5-ad75-efbc2fab7892, amqp_consumerTag=amq.ctag-RoDWmfMwM4OmjWLdmPL2Hw, contentType=application/json, timestamp=1567059315403}]
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:234)
	at org.springframework.cloud.stream.converter.ApplicationJsonMessageMarshallingConverter.convertFromInternal(ApplicationJsonMessageMarshallingConverter.java:105)
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:181)
```

Great Appreciate where is the issue here

**Comment by Tapsprofile** [comment]
Any update , as this where I have been stuck to use the spring cloud bus.

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Can you show me the definition of `BootEvent`?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
