### ISSUE TITLE
spring bus JSON deserealization problems while moving from springboot 2.0.2 to 2.2.2

### ISSUE THREAD

**Issue by creif** [spring-cloud/spring-cloud-bus#213]
I am moving my project from spring boot 2.0.2 to 2.2.2 , and also from java 8 to java 11. During this an error of deserialization of jsons appeared while refreshing spring bus. The project starts correctly , but when I execute refresh from the server following errors appear in its log (the same server consumes the refresh message in order to simplify debugging of this problem,actually several services consume refresh message)
```
2019-12-18 22:54:02.311 [springCloudBus.anonymous.n-VZyfkBSDGKA1l4NdRXWQ-1] ERROR o.s.i.handler.LoggingHandler.[handleMessageInternal:187] []- org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Could not resolve type id 'RefreshRemoteApplicationEvent' as a subtype of org.springframework.cloud.bus.event.RemoteApplicationEvent`: known type ids = []
 at [Source: (byte[])"{"type":"RefreshRemoteApplicationEvent","timestamp":1576702439248,"originService":"config-server:8888:6e0d310ef7bf7a5a08e730d42577a1c5","destinationService":"**","id":"514210a8-3b49-408b-99be-c61ea17ecf98"}"; line: 1, column: 9]; nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'RefreshRemoteApplicationEvent' as a subtype of org.springframework.cloud.bus.event.RemoteApplicationEvent`: known type ids = []
 at [Source: (byte[])"{"type":"RefreshRemoteApplicationEvent","timestamp":1576702439248,"originService":"config-server:8888:6e0d310ef7bf7a5a08e730d42577a1c5","destinationService":"**","id":"514210a8-3b49-408b-99be-c61ea17ecf98"}"; line: 1, column: 9], failedMessage=GenericMessage [payload=byte[206], headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=1, deliveryAttempt=3, amqp_consumerQueue=springCloudBus.anonymous.n-VZyfkBSDGKA1l4NdRXWQ, amqp_redelivered=false, amqp_receivedRoutingKey=springCloudBus, amqp_timestamp=Wed Dec 18 22:53:59 IST 2019, amqp_messageId=64f6351b-cb29-2e06-2f02-2426e8ba6fea, id=3c2ff3ce-c8f0-aca6-6709-a216ee8552ab, amqp_consumerTag=amq.ctag-EdTdjMFj3XcJuKkSEalCgA, sourceData=(Body:'{"type":"RefreshRemoteApplicationEvent","timestamp":1576702439248,"originService":"config-server:8888:6e0d310ef7bf7a5a08e730d42577a1c5","destinationService":"**","id":"514210a8-3b49-408b-99be-c61ea17ecf98"}' MessageProperties [headers={}, timestamp=Wed Dec 18 22:53:59 IST 2019, messageId=64f6351b-cb29-2e06-2f02-2426e8ba6fea, contentType=application/json, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=false, receivedExchange=springCloudBus, receivedRoutingKey=springCloudBus, deliveryTag=1, consumerTag=amq.ctag-EdTdjMFj3XcJuKkSEalCgA, consumerQueue=springCloudBus.anonymous.n-VZyfkBSDGKA1l4NdRXWQ]), contentType=application/json, timestamp=1576702439300}]
    at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:235)
    at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:197)
    at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:70)
    at org.springframework.cloud.stream.config.SmartPayloadArgumentResolver.resolveArgument(SmartPayloadArgumentResolver.java:115)
    at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117)
    at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:148)
    at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116)
    at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
    at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:127)
    at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170)
    at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
    at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
    at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
    at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
    at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
    at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:198)
    at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$1300(AmqpInboundChannelAdapter.java:61)
    at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.lambda$onMessage$0(AmqpInboundChannelAdapter.java:239)
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
    at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:236)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1569)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1488)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1476)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1467)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1411)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:958)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:908)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:81)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1279)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1185)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'RefreshRemoteApplicationEvent' as a subtype of `org.springframework.cloud.bus.event.RemoteApplicationEvent`: known type ids = []
 at [Source: (byte[])"{"type":"RefreshRemoteApplicationEvent","timestamp":1576702439248,"originService":"config-server:8888:6e0d310ef7bf7a5a08e730d42577a1c5","destinationService":"**","id":"514210a8-3b49-408b-99be-c61ea17ecf98"}"; line: 1, column: 9]
    at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
    at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1758)
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1265)
    at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:290)
    at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:162)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
    at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
    at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3300)
    at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:219)
    ... 36 more


2019-12-18 22:54:02.316 [AMQP Connection 127.0.0.1:5672] ERROR o.s.a.r.c.CachingConnectionFactory.[log:1567] []- Channel shutdown: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'DLX' in vhost '/', class-id=60, method-id=40)

```

```

2019-12-18 22:54:06.837 [springCloudBus.anonymous.n-VZyfkBSDGKA1l4NdRXWQ-1] ERROR o.s.i.handler.LoggingHandler.[handleMessageInternal:187] []- org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Could not resolve type id 'AckRemoteApplicationEvent' as a subtype of org.springframework.cloud.bus.event.RemoteApplicationEvent`: known type ids = []
 at [Source: (byte[])"{"type":"AckRemoteApplicationEvent","timestamp":1576702443815,"originService":"spring-boot-admin:8087:416d6b96321b5c4b16be8b2231b80ce9","destinationService":"**","id":"e2b260c2-d94b-4b95-9905-a9ba40db7fdb","ackId":"514210a8-3b49-408b-99be-c61ea17ecf98","ackDestinationService":"**","event":"org.springframework.cloud.bus.event.RefreshRemoteApplicationEvent"}"; line: 1, column: 9]; nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id AckRemoteApplicationEvent' as a subtype of `org.springframework.cloud.bus.event.RemoteApplicationEvent`: known type ids = []
 at [Source: (byte[])"{"type":"AckRemoteApplicationEvent","timestamp":1576702443815,"originService":"spring-boot-admin:8087:416d6b96321b5c4b16be8b2231b80ce9","destinationService":"**","id":"e2b260c2-d94b-4b95-9905-a9ba40db7fdb","ackId":"514210a8-3b49-408b-99be-c61ea17ecf98","ackDestinationService":"**","event":"org.springframework.cloud.bus.event.RefreshRemoteApplicationEvent"}"; line: 1, column: 9], failedMessage=GenericMessage [payload=byte[358], headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedExchange=springCloudBus, amqp_deliveryTag=2, deliveryAttempt=3, amqp_consumerQueue=springCloudBus.anonymous.n-VZyfkBSDGKA1l4NdRXWQ, amqp_redelivered=false, amqp_receivedRoutingKey=springCloudBus, amqp_timestamp=Wed Dec 18 22:54:03 IST 2019, amqp_messageId=f9e5dc7e-2365-797f-e078-d62c78a42e43, id=b3c94b70-64dc-f461-036c-7f496b0928e7, amqp_consumerTag=amq.ctag-EdTdjMFj3XcJuKkSEalCgA, sourceData=(Body:'{"type":"AckRemoteApplicationEvent","timestamp":1576702443815,"originService":"spring-boot-admin:8087:416d6b96321b5c4b16be8b2231b80ce9","destinationService":"**","id":"e2b260c2-d94b-4b95-9905-a9ba40db7fdb","ackId":"514210a8-3b49-408b-99be-c61ea17ecf98","ackDestinationService":"**","event":"org.springframework.cloud.bus.event.RefreshRemoteApplicationEvent"}' MessageProperties [headers={}, timestamp=Wed Dec 18 22:54:03 IST 2019, messageId=f9e5dc7e-2365-797f-e078-d62c78a42e43, contentType=application/json, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=false, receivedExchange=springCloudBus, receivedRoutingKey=springCloudBus, deliveryTag=2, consumerTag=amq.ctag-EdTdjMFj3XcJuKkSEalCgA, consumerQueue=springCloudBus.anonymous.n-VZyfkBSDGKA1l4NdRXWQ]), contentType=application/json, timestamp=1576702443835}]
    at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:235)
    at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:197)
    at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:70)
    at org.springframework.cloud.stream.config.SmartPayloadArgumentResolver.resolveArgument(SmartPayloadArgumentResolver.java:115)
    at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117)
    at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:148)
    at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116)
    at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
    at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:127)
    at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170)
    at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
    at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
    at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
    at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
    at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
    at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:198)
    at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$1300(AmqpInboundChannelAdapter.java:61)
    at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.lambda$onMessage$0(AmqpInboundChannelAdapter.java:239)
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
    at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:236)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1569)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1488)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1476)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1467)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1411)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:958)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:908)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:81)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1279)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1185)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'AckRemoteApplicationEvent' as a subtype of `org.springframework.cloud.bus.event.RemoteApplicationEvent`: known type ids = []
 at [Source: (byte[])"{"type":"AckRemoteApplicationEvent","timestamp":1576702443815,"originService":"spring-boot-admin:8087:416d6b96321b5c4b16be8b2231b80ce9","destinationService":"**","id":"e2b260c2-d94b-4b95-9905-a9ba40db7fdb","ackId":"514210a8-3b49-408b-99be-c61ea17ecf98","ackDestinationService":"**","event":"org.springframework.cloud.bus.event.RefreshRemoteApplicationEvent"}"; line: 1, column: 9]
    at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
    at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1758)
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1265)
    at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:290)
    at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:162)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
    at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
    at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3300)
    at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:219)
    ... 36 more
2019-12-18 22:54:06.840 [AMQP Connection 127.0.0.1:5672] ERROR o.s.a.r.c.CachingConnectionFactory.[log:1567] []- Channel shutdown: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'DLX' in vhost '/', class-id=60, method-id=40)
```
When I start project on openjdk 11 with springboot 2.0.2 everything works fine. While debugging this problem I saw that upon consuming the refresh message jackson is unable to create deserializers for subtypes of RemoteApplicationEvent. But during serialization of the same message is successful and 4 serializers are created. I thought that it is some kind of versions clash of dependencies but still unable to find it. Below are versions of main dependencies in the project :

```
      <spring-boot-version>2.2.2.RELEASE</spring-boot-version>
      <spring-version>5.2.2.RELEASE</spring-version>
       <swagger-version>2.9.2</swagger-version>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
       <common.kafka.version>1.0.8</common.kafka.version>
      <spring.cloud.version>Hoxton.RELEASE</spring.cloud.version>
     <spring.cloud.config.version>2.2.0.RELEASE</spring.cloud.config.version>
       <spring-boot-admin.version>2.2.0</spring-boot-admin.version>
       <com.fasterxml.jackson.version>2.10.1</com.fasterxml.jackson.version>
      <cassandra.unit.test>3.5.0.1</cassandra.unit.test>
       <redisson.version>3.11.6</redisson.version>
      <swagger-annotations.version>1.5.24</swagger-annotations.version>
       <lombok.version>1.18.10</lombok.version>
       <spotbugs.version>3.1.12</spotbugs.version>
```

below attaching results of execution of mvn dependency:tree -Dverbose in the relevant module:
[dependencies.txt](https://github.com/spring-cloud/spring-cloud-bus/files/3985364/dependencies.txt)

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by creif** [comment]
tried to format code as written in formatting instructions.
Attached "mvn dependency:tree" results of module instead of pom contents.

**Comment by creif** [comment]
After I downgraded spring boot to 2.1.11 , spring cloud to Greenwich.RELEASE.
Refresh works correctly and no desalinization errors are present.
```
        <spring-boot-version>2.1.11.RELEASE</spring-boot-version>
        <spring-version>5.1.12.RELEASE</spring-version>
        <swagger-version>2.9.2</swagger-version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <common.kafka.version>1.0.8</common.kafka.version>
        <spring.cloud.version>Greenwich.RELEASE</spring.cloud.version>
        <spring.cloud.config.version>2.1.0.RELEASE</spring.cloud.config.version>
        <spring-boot-admin.version>2.1.0</spring-boot-admin.version>
        <com.fasterxml.jackson.version>2.9.10</com.fasterxml.jackson.version>
        <cassandra.unit.test>3.5.0.1</cassandra.unit.test>
        <redisson.version>3.11.6</redisson.version>
        <swagger-annotations.version>1.5.24</swagger-annotations.version>
        <lombok.version>1.18.10</lombok.version>
        <spotbugs.version>3.1.12</spotbugs.version>
        <groovy.all.version>2.5.8</groovy.all.version>
```

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by creif** [comment]
Hi,
I found the root cause of the error.
I use rabbit in my project as bus . In its configuration there are several beans that conflict with spring cloud and cause the error.
More specific in class RabbitMQConfiguration which implements RabbitListenerConfigurer 
I have 

```
    @Bean
    public DefaultMessageHandlerMethodFactory messageHandlerMethodFactory()
    {
        DefaultMessageHandlerMethodFactory factory = new DefaultMessageHandlerMethodFactory();
        factory.setMessageConverter(consumerJackson2MessageConverter());
        return factory;
    }

    /**
     * Convert message using jackson
     *
     * @return MappingJackson2MessageConverter
     */
    @Bean 
    public MappingJackson2MessageConverter consumerJackson2MessageConverter()
    {
        return new MappingJackson2MessageConverter();
    }
```

once I remove consumerJackson2MessageConverter bean bus refresh works correctly.
If those beans are present than bus refresh causes errors.

Can you please tell me why consumerJackson2MessageConverter  can cause this error ,and how should be fixed.

Thanks

**Comment by creif** [comment]
After I configured consumerJackson2MessageConverter following way with objectMapper autowired from JacksonAutoConfiguration everything started to work.
```
    @Bean 
    public MappingJackson2MessageConverter consumerJackson2MessageConverter()
    {
        final MappingJackson2MessageConverter mappingJackson2MessageConverter = new MappingJackson2MessageConverter();
        mappingJackson2MessageConverter.setObjectMapper(objectMapper);
        return mappingJackson2MessageConverter;
    }
```

**Comment by nikbali** [comment]
I had same error. I added annotation BusJacksonAutoConfiguration. That resolved my problem.

So try to add this in your configuration:

`@Import({BusJacksonAutoConfiguration.class, BusAutoConfiguration.class})`
