### ISSUE TITLE
Can someone please provide a sample app using Spring Cloud Bus with Config Server and Spring Boot Client App

### ISSUE THREAD

**Issue by jgawli** [spring-cloud/spring-cloud-bus#24]
I have a Config Server and a Spring Boot Client app and I am trying to use Spring Cloud Bus for dynamic updates of configuration properties but not able to set it. I have RabbitMQ set on Linus box and these properties in application.properties file of Config Server 
````
spring.rabbitmq.dynamic=true
spring.rabbitmq.host=server ip
spring.rabbitmq.port=5672
spring.rabbitmq.virtual-host=my-vhost
spring.rabbitmq.username=user1
spring.rabbitmq.password=password
````
and I also added spring-cloud-bus-parent, and spring-cloud-starter-bus-amqp dependency. What else do I need to do other than this. I am trying to create exchange and queue like this 
````
@SpringBootApplication
@EnableConfigServer
public class ConfigServerApplication implements CommandLineRunner
{
    public static void main( String[] args )
    {
        SpringApplication.run(ConfigServerApplication.class, args);
    }

    @Bean
    Queue queue() {
        return new Queue("my-queue", false);
    }

    @Bean
    TopicExchange exchange() {
        return new TopicExchange("my-exchange");
    }

    @Bean
    Binding binding(Queue queue, TopicExchange exchange) {
        return BindingBuilder.bind(queue).to(exchange).with("my-queue");
    }

    @Autowired
    private Sender sender;

    @Override
    public void run(String... args) throws Exception {
        sender.sendToRabbitmq(new Object());
    }
}

@Service
class Sender {

    @Autowired
    private RabbitMessagingTemplate rabbitMessagingTemplate;
    @Autowired
    private MappingJackson2MessageConverter mappingJackson2MessageConverter;

    public void sendToRabbitmq(final Object o) {

        //this.rabbitMessagingTemplate.setMessageConverter(this.mappingJackson2MessageConverter);

        this.rabbitMessagingTemplate.convertAndSend("my-exchange", "my-queue", o);

    }

}
````
But when I start my Config Server app, it gives me this error: 
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '8f223d29-53c5-4d79-b54e-395fe233c6f9' in vhost 'my-vhost', class-id=50, method-id=10)

I don't know what I am missing. Please help. Would be great if there is a sample app.

**Comment by spencergibb** [comment]
Without trying to diagnose your problem, we have a sample in https://github.com/spring-cloud-samples/customers-stores. It uses https://github.com/spring-cloud-samples/configserver which in turn uses https://github.com/spring-cloud-samples/config-repo as it's git source.

**Comment by jgawli** [comment]
Thank you very Spencer but the example you gave uses rabbitmq on localhost but do we configure queues and exchange for rabbitmq on remote server. In my example I am using remote rabbitmq and the documentation says I have to use Spring Cloud Connectors to configure it in my application. I was trying to create exchange and queue using rabbitmq admin but was unable to do that. Please let me know what I am missing or doing wrong.

Thank you.

**Comment by garyrussell** [comment]
This...

`no queue '8f223d29-53c5-4d79-b54e-395fe233c6f9' `

...implies you have an `AnonymousQueue` someplace (used by a listener container or `@RabbitListener`)

I don't see any listener configuration or anonymous queue in the configuration above.

**Comment by garyrussell** [comment]
Can you show the complete stack trace?

Also turn on DEBUG logging for `org.springframework`; it will provide copious information about bean wiring and queue declarations etc.

**Comment by jgawli** [comment]
I added these 2 classes and configuration properties in Spring Boot Client app follows:
# RabbitMQ Properties
spring.rabbitmq.addresses: ${vcap.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:remote server ip}:${RABBITMQ_PORT:5672}}
spring.rabbitmq.dynamic=true
spring.rabbitmq.host=remote server ip
spring.rabbitmq.port=5672
spring.rabbitmq.virtual-host=cep-host
spring.rabbitmq.username=cep
spring.rabbitmq.password=cep123

@Configuration
public class RabbitMqConfig {

    private static final String SIMPLE_MESSAGE_QUEUE = "simple.queue.name";

    @Autowired
    private ConnectionFactory rabbitConnectionFactory;

    @Bean
    public Queue simpleQueue() {
        return new Queue(SIMPLE_MESSAGE_QUEUE);
    }

    @Bean
    public RabbitTemplate rabbitTemplate() {
        RabbitTemplate template = new RabbitTemplate(rabbitConnectionFactory);
        template.setRoutingKey(SIMPLE_MESSAGE_QUEUE);
        return template;
    }

    @Bean
    public SimpleMessageListenerContainer listenerContainer() {
        SimpleMessageListenerContainer listenerContainer = new SimpleMessageListenerContainer();
        listenerContainer.setConnectionFactory(rabbitConnectionFactory);
        listenerContainer.setQueues(simpleQueue());
        listenerContainer.setMessageListener(new Consumer());
        listenerContainer.setAcknowledgeMode(AcknowledgeMode.AUTO);
        return listenerContainer;
    }
}

And Consumer class:
public class Consumer implements MessageListener {

    @Override
    public void onMessage(Message message) {
        System.out.println(new String(message.getBody()));
    }
}

I get following error:
2015-12-10 11:38:35,287 [main] INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer  : Tomcat started on port(s): 8080 (http)
 2015-12-10 11:38:35,287 [main] DEBUG o.s.b.f.s.DefaultListableBeanFactory  : Returning cached instance of singleton bean 'org.springframework.integration.internalMessagingAnnotationPostProcessor'
 2015-12-10 11:38:37,126 [SimpleAsyncTaskExecutor-2] WARN  o.s.a.r.l.SimpleMessageListenerContainer  : Consumer raised exception, processing can restart if the connection factory supports it
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:189) ~[na:1.8.0_25]
	at java.net.SocketInputStream.read(SocketInputStream.java:121) ~[na:1.8.0_25]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_25]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_25]
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[na:1.8.0_25]
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95) ~[amqp-client-3.5.1.jar:na]
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139) ~[amqp-client-3.5.1.jar:na]
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:534) ~[amqp-client-3.5.1.jar:na]
	... 1 common frames omitted
Wrapped by: com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67) ~[amqp-client-3.5.1.jar:na]
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33) ~[amqp-client-3.5.1.jar:na]
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:348) ~[amqp-client-3.5.1.jar:na]
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:221) ~[amqp-client-3.5.1.jar:na]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118) ~[amqp-client-3.5.1.jar:na]
	... 10 common frames omitted
Wrapped by: java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106) ~[amqp-client-3.5.1.jar:na]
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102) ~[amqp-client-3.5.1.jar:na]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:124) ~[amqp-client-3.5.1.jar:na]
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:376) ~[amqp-client-3.5.1.jar:na]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:603) ~[amqp-client-3.5.1.jar:na]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:204) ~[spring-rabbit-1.4.5.RELEASE.jar:na]
	... 7 common frames omitted
Wrapped by: org.springframework.amqp.AmqpIOException: java.io.IOException
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:63) ~[spring-rabbit-1.4.5.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:217) ~[spring-rabbit-1.4.5.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:444) ~[spring-rabbit-1.4.5.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createConnection(ConnectionFactoryUtils.java:80) ~[spring-rabbit-1.4.5.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:130) ~[spring-rabbit-1.4.5.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:67) ~[spring-rabbit-1.4.5.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:434) ~[spring-rabbit-1.4.5.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1083) ~[spring-rabbit-1.4.5.RELEASE.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
 2015-12-10 11:38:37,127 [SimpleAsyncTaskExecutor-2] INFO  o.s.a.r.l.SimpleMessageListenerContainer  : Restarting Consumer: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
 2015-12-10 11:38:37,127 [SimpleAsyncTaskExecutor-2] DEBUG o.s.a.r.l.BlockingQueueConsumer  : Closing Rabbit Channel: null
 2015-12-10 11:38:37,130 [SimpleAsyncTaskExecutor-3] DEBUG o.s.a.r.l.BlockingQueueConsumer  : Starting consumer Consumer: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
 2015-12-10 11:38:38,337 [SimpleAsyncTaskExecutor-2] ERROR o.s.a.r.l.SimpleMessageListenerContainer  : Failed to check/redeclare auto-delete queue(s).

**Comment by garyrussell** [comment]
>2015-12-10 11:38:37,126 [SimpleAsyncTaskExecutor-2] WARN  o.s.a.r.l.SimpleMessageListenerContainer  : Consumer raised exception, processing can restart if the connection factory supports it
java.net.SocketException: Connection reset

This is generally caused by bad credentials - the AMQP spec says the server will close the connection if it receives bad credentials.

Check the rabbitmq server log.

**Comment by jgawli** [comment]
But am I missing anything in my code, do I need to add a Producer class in Config Server.

**Comment by garyrussell** [comment]
I am not sure what you mean.

**Comment by jgawli** [comment]
I keep getting this error, I just don't know what am I missing

2015-12-16 14:20:41.601  WARN 52288 --- [cTaskExecutor-1] o.s.a.r.listener.BlockingQueueConsumer   : Queue declaration failed; retries left=1

org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException: Failed to declare queue(s):[efm-queue]
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:554)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:453)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1083)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:124)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:885)
	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:666)
	at com.sun.proxy.$Proxy61.queueDeclarePassive(Unknown Source)
	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:533)
	... 3 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'efm-queue' in vhost 'cep-vhost', class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:361)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:226)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118)
	... 12 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'efm-queue' in vhost 'cep-vhost', class-id=50, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:484)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:321)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:144)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:91)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:554)

**Comment by jgawli** [comment]
I declared a queue and a MessageListener but I keep getting this error. Do I have to explicitly create a queue in RabbitMq first.

**Comment by dsyer** [comment]
No, you do not. You need to configure the correct credentials for rabbitmq.

**Comment by lidong1665** [comment]
2017-02-24 11:38:14,708  ERROR [org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer] - Failed to check/redeclare auto-delete queue(s).
org.springframework.amqp.AmqpIOException: java.io.IOException
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:71)
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:366)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:547)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1430)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1411)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1387)
	at org.springframework.amqp.rabbit.core.RabbitAdmin.getQueueProperties(RabbitAdmin.java:336)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.redeclareElementsIfNecessary(SimpleMessageListenerContainer.java:1114)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1100(SimpleMessageListenerContainer.java:95)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1333)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:105)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:101)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:123)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:381)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:99)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:900)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:859)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1000)
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:354)
	... 9 more
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=530, reply-text=NOT_ALLOWED - access to vhost 'vhostld' refused for user 'guest', class-id=10, method-id=40)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:32)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:366)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:229)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:117)
	... 16 more
2017-02-24 11:38:14,710  WARN  [com.rabbitmq.client.impl.ForgivingExceptionHandler] - An unexpected connection driver error occured (Exception message: Socket closed)
2017-02-24 11:38:14,732  WARN  [com.rabbitmq.client.impl.ForgivingExceptionHandler] - An unexpected connection driver error occured (Exception message: Socket closed)
2017-02-24 11:38:14,741  ERROR [org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer] - Failed to check/redeclare auto-delete queue(s).
org.springframework.amqp.AmqpIOException: java.io.IOException
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:71)
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:366)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:547)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1430)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1411)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1387)
	at org.springframework.amqp.rabbit.core.RabbitAdmin.getQueueProperties(RabbitAdmin.java:336)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.redeclareElementsIfNecessary(SimpleMessageListenerContainer.java:1114)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1100(SimpleMessageListenerContainer.java:95)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1333)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:105)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:101)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:123)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:381)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:99)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:900)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:859)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1000)
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:354)
	... 9 more
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=530, reply-text=NOT_ALLOWED - access to vhost 'vhostld' refused for user 'guest', class-id=10, method-id=40)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:32)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:366)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:229)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:117)
	... 16 more

**Comment by dsyer** [comment]
This looks like the problem:

```
access to vhost 'vhostld' refused for user 'guest',
```
