### ISSUE TITLE
Using Spring-cloud-bus-amqp  with RabbitMQ when starting failed in docker.

### ISSUE THREAD

**Issue by chutian52** [spring-cloud/spring-cloud-bus#73]
When we start our springboot application. we found that there's a error occured.
We checked  RabbitMQ's log found 
```
=WARNING REPORT==== 19-Jun-2017::16:39:07 ===
closing AMQP connection <0.23162.1> (172.18.66.9:46976 -> 172.18.184.15:5672 - rabbitConnectionFactory#0, vhost: '/', user: 'spring'):
client unexpectedly closed TCP connection

=INFO REPORT==== 19-Jun-2017::16:39:22 ===
accepting AMQP connection <0.23260.1> (172.18.66.9:49886 -> 172.18.184.15:5672)

=INFO REPORT==== 19-Jun-2017::16:39:22 ===
Connection <0.23260.1> (172.18.66.9:49886 -> 172.18.184.15:5672) has a client-provided name: rabbitConnectionFactory#0

=INFO REPORT==== 19-Jun-2017::16:39:22 ===
connection <0.23260.1> (172.18.66.9:49886 -> 172.18.184.15:5672 - rabbitConnectionFactory#0): user 'spring' authenticated and granted access to vhost '/'

=INFO REPORT==== 19-Jun-2017::16:39:23 ===
closing AMQP connection <0.23260.1> (172.18.66.9:49886 -> 172.18.184.15:5672 - rabbitConnectionFactory#0, vhost: '/', user: 'spring')

=INFO REPORT==== 19-Jun-2017::16:39:24 ===
accepting AMQP connection <0.23279.1> (172.18.66.9:49894 -> 172.18.184.15:5672)

=INFO REPORT==== 19-Jun-2017::16:39:24 ===
Connection <0.23279.1> (172.18.66.9:49894 -> 172.18.184.15:5672) has a client-provided name: rabbitConnectionFactory#1

=INFO REPORT==== 19-Jun-2017::16:39:24 ===
connection <0.23279.1> (172.18.66.9:49894 -> 172.18.184.15:5672 - rabbitConnectionFactory#1): user 'spring' authenticated and granted access to vhost '/'

=WARNING REPORT==== 19-Jun-2017::16:39:27 ===
closing AMQP connection <0.23184.1> (172.18.66.8:50206 -> 172.18.184.15:5672 - rabbitConnectionFactory#0, vhost: '/', user: 'spring'):
client unexpectedly closed TCP connection

=ERROR REPORT==== 19-Jun-2017::16:39:29 ===
Channel error on connection <0.23279.1> (172.18.66.9:49894 -> 172.18.184.15:5672, vhost: '/', user: 'spring'), channel 1:
operation queue.declare caused a channel exception not_found: no queue 'springCloudBus.anonymous.ZOxrMvtrTWOfD9i4ZumMcg' in vhost '/'

=ERROR REPORT==== 19-Jun-2017::16:39:34 ===
Channel error on connection <0.23279.1> (172.18.66.9:49894 -> 172.18.184.15:5672, vhost: '/', user: 'spring'), channel 1:
operation queue.declare caused a channel exception not_found: no queue 'springCloudBus.anonymous.ZOxrMvtrTWOfD9i4ZumMcg' in vhost '/'

=ERROR REPORT==== 19-Jun-2017::16:39:39 ===
Channel error on connection <0.23279.1> (172.18.66.9:49894 -> 172.18.184.15:5672, vhost: '/', user: 'spring'), channel 1:
operation queue.declare caused a channel exception not_found: no queue 'springCloudBus.anonymous.ZOxrMvtrTWOfD9i4ZumMcg' in vhost '/'
```

And Spring Rabbit auto recovery when connection closed. but there's a  issue in RabbitExchangeQueueProvisioner.java  

```
@Override
	public ConsumerDestination provisionConsumerDestination(String name, String group, ExtendedConsumerProperties<RabbitConsumerProperties> properties) {
		boolean anonymous = !StringUtils.hasText(group);
		String baseQueueName = anonymous ? groupedName(name, ANONYMOUS_GROUP_NAME_GENERATOR.generateName())
				: groupedName(name, group);
		if (this.logger.isInfoEnabled()) {
			this.logger.info("declaring queue for inbound: " + baseQueueName + ", bound to: " + name);
		}
		String prefix = properties.getExtension().getPrefix();
		final String exchangeName = applyPrefix(prefix, name);
		Exchange exchange = buildExchange(properties.getExtension(), exchangeName);
		if (properties.getExtension().isDeclareExchange()) {
			declareExchange(exchangeName, exchange);
		}
		String queueName = applyPrefix(prefix, baseQueueName);
		boolean partitioned = !anonymous && properties.isPartitioned();
		boolean durable = !anonymous && properties.getExtension().isDurableSubscription();
		Queue queue;
		if (anonymous) {
			queue = new Queue(queueName, false, true, true, queueArgs(queueName, properties.getExtension(), false));
		}
		else {
			if (partitioned) {
				String partitionSuffix = "-" + properties.getInstanceIndex();
				queueName += partitionSuffix;
			}
			if (durable) {
				queue = new Queue(queueName, true, false, false,
						queueArgs(queueName, properties.getExtension(), false));
			}
			else {
				queue = new Queue(queueName, false, false, true,
						queueArgs(queueName, properties.getExtension(), false));
			}
		}
```

In RabbitMQ, we queueName declared  by annother connection,it would throw IOException in com.rabbitmq.client.impl.ChannelN.java 

```
    /** Public API - {@inheritDoc} */
    @Override
    public Queue.DeclareOk queueDeclarePassive(String queue)
        throws IOException
    {
        validateQueueNameLength(queue);
        return (Queue.DeclareOk)
               exnWrappingRpc(new Queue.Declare.Builder()
                               .queue(queue)
                               .passive()
                               .exclusive()
                               .autoDelete()
                              .build())
               .getMethod();
    }
```

There are two conditions may cause IOException: queue not exists or queue Declared  by annother connection.
We thought that if connection#0 closed unexpectedly  when network partition happed. connection#2 connection recovery but cannot declared agained.

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

I have no idea. Can you isolate spring-cloud-stream-amqp and see if there is a problem there as opposed to the bus?

Maybe @dsyer or @garyrussell have some kind of idea.

**Comment by garyrussell** [comment]
I just ran a test and the queue was properly redeclared when the connection was recovered, as expected...

```
2017-07-01 09:54:56.096 ERROR 2149 --- [ 127.0.0.1:5672] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - Closed via management plugin, class-id=0, method-id=0)
2017-07-01 09:54:57.093  INFO 2149 --- [4Kt9I7UyZDuhg-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@68dfda77: tags=[{amq.ctag-FY84k1aPTKT2eTSXKRbFvg=springCloudBus.anonymous.zBkOjgl_S4Kt9I7UyZDuhg}], channel=Cached Rabbit Channel: AMQChannel(amqp://guest@127.0.0.1:5672/,1), conn: Proxy@10f405ff Shared Rabbit Connection: SimpleConnection@11a3a45f [delegate=amqp://guest@127.0.0.1:5672/, localPort= 50527], acknowledgeMode=AUTO local queue size=0
2017-07-01 09:54:57.102  INFO 2149 --- [4Kt9I7UyZDuhg-2] o.s.a.r.c.CachingConnectionFactory       : Created new connection: rabbitConnectionFactory#13250132:1/SimpleConnection@6185f44 [delegate=amqp://guest@127.0.0.1:5672/, localPort= 50538]
2017-07-01 09:54:57.104  INFO 2149 --- [4Kt9I7UyZDuhg-2] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (springCloudBus.anonymous.zBkOjgl_S4Kt9I7UyZDuhg) durable:false, auto-delete:true, exclusive:true. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
```

What do you see in your Boot log?

**Comment by imxuthus** [comment]
@garyrussell hi, i have same issue like this
when mq cluster 5th node down and restart , rabbitmq logs shows like same.
```
=ERROR REPORT==== 04-Oct-2017::02:41:29 ===
Channel error on connection  (xxxxxxxxxxx, vhost: '/', user: 'admin'), channel 1:
operation queue.declare caused a channel exception not_found: no queue 'springCloudBus.anonymous.xxxxxxxxxxxxxxxxxxxxx' in vhost '/'
```

other queues all ok. only use springCloudBus recovery failure.
and my 10 consumers(docker node) not reconnect this node anymore.
Queues tab shows
    springCloudBus in node 1-4
    **aQueue0-4 at node 1-5 (1-4 have 20 consumers, 5 no consumers)**

but, when i add a new consumer(docker node).
node 1-4 show 22 consumers to connect. node 5 show 2 consumers.
Queues tab shows
    springCloudBus in node 1-4
    **aQueue0-4 at node 1-5 (1-4 have 20 consumers and 2 new consumers, 5 have 2 new consumers)**
Channels/Connections tab shows
    **have multi new consumer docker ip with node 1-4, but no node 5.**

my env is rabbitmq have 5 node
springCloudBus Type:topic Durable:true
To                                                                          Routingkey      Arguments
spingCloudBus.anonymous.xxxxxxxxxxxxxxxx       #                                                  Unbind
....

a.Exchange Type:direct Durable:true
To                Routingkey      Arguments
aQueue0      queue0                                 Unbind
aQueue1      queue1                                 Unbind
aQueue2      queue2                                 Unbind
aQueue3      queue3                                 Unbind
aQueue4      queue4                                 Unbind

any idea? thank you~

**Comment by xd03122049** [comment]
anyone can solve this problem, i have same issue and client can't startup,
and when i add dependenecy in pom.xml
```
<dependency>
      <groupId>org.springframework.retry</groupId>
      <artifactId>spring-retry</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-bus-amqp</artifactId>
    </dependency>
```
which encounter the same problem.
But when i remove these dependency and use "/refresh", it did work well, and again add it, i surpringly find i work well. and i don't kown why it work well

**Comment by garyrussell** [comment]
@imxuthus Please show the logs from the Spring side; the server log is not much use.

@xd03122049 Please provide logs that exhibit the behavior.

**Comment by xd03122049** [comment]
but i'm sorry i can't reappear the occurance. So ican't provide the log,but i search there because i find like 
`=ERROR REPORT==== 04-Oct-2017::02:41:29 ===
Channel error on connection  (xxxxxxxxxxx, vhost: '/', user: 'admin'), channel 1:
operation queue.declare caused a channel exception not_found: no queue 'springCloudBus.anonymous.xxxxxxxxxxxxxxxxxxxxx' in vhost '/'`,  i remember i will provide the error log next, and i hope find the answer from here.

**Comment by pkuashi** [comment]
I run into the same issue, the spring log is below. Spring cloud bus version: 1.2.1.RELEASE

```
   2018-01-02T12:00:19.93+0800 [APP/0] OUT 2018-01-02 04:00:19,933 WARN  springCloudBus.anonymous.-c3wkgsvQ_W2e9F0U9wpwg-3  o.s.a.r.l.BlockingQueueConsumer:581 - Failed to declare queue:springCloudBus.anonymous.-c3wkgsvQ_W2e9F0U9wpwg 
   2018-01-02T12:00:19.94+0800 [APP/0] OUT org.springframework.amqp.rabbit.listener.QueuesNotAvailableException: Cannot prepare queue for listener. Either the queue doesn't exist or the broker will not allow us to use it.
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:514) ~[spring-rabbit-1.6.1.RELEASE.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1280) ~[spring-rabbit-1.6.1.RELEASE.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT Caused by: org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException: Failed to declare queue(s):[springCloudBus.anonymous.-c3wkgsvQ_W2e9F0U9wpwg]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:587) ~[spring-rabbit-1.6.1.RELEASE.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:486) ~[spring-rabbit-1.6.1.RELEASE.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	... 2 common frames omitted
   2018-01-02T12:00:19.94+0800 [APP/0] OUT Caused by: java.io.IOException: null
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:124) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:885) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.ChannelN.queueDeclarePassive(ChannelN.java:61) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:916) ~[spring-rabbit-1.6.1.RELEASE.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.sun.proxy.$Proxy136.queueDeclarePassive(Unknown Source) ~[na:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.attemptPassiveDeclarations(BlockingQueueConsumer.java:566) ~[spring-rabbit-1.6.1.RELEASE.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	... 3 common frames omitted
   2018-01-02T12:00:19.94+0800 [APP/0] OUT Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'springCloudBus.anonymous.-c3wkgsvQ_W2e9F0U9wpwg' in vhost '/', class-id=50, method-id=10)
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:361) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:226) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	... 12 common frames omitted
   2018-01-02T12:00:19.94+0800 [APP/0] OUT Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'springCloudBus.anonymous.-c3wkgsvQ_W2e9F0U9wpwg' in vhost '/', class-id=50, method-id=10)
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:484) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:321) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:144) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:91) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:560) ~[amqp-client-3.6.3.jar!/:na]
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 	... 1 common frames omitted
   2018-01-02T12:00:19.94+0800 [APP/0] OUT 2018-01-02 04:00:19,945 ERROR springCloudBus.anonymous.-c3wkgsvQ_W2e9F0U9wpwg-3  o.s.a.r.l.SimpleMessageListenerContainer:1448 - Stopping container from aborted consumer 
```

**Comment by garyrussell** [comment]
We need to see the log before that, when the initial problem occurred; that is simply logging that the queue is missing; when the connection is lost, the queue should automatically be redeclared.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by pcornelissen** [comment]
I have the same problem. I even restarted the rabbitMQ Cluster and the application, but the problems seems to persist...

This is the log, before this there is just logging from my controller when it processes the request.

```
29.1.2018 06:49:402018-01-29 06:49:40.710 ERROR 11 --- [.42.34.187:5672] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: connection error
29.1.2018 06:49:402018-01-29 06:49:40.711 ERROR 11 --- [.42.34.187:5672] o.s.a.r.c.CachingConnectionFactory       : Channel shutdown: connection error
29.1.2018 06:49:402018-01-29 06:49:40.715  INFO 11 --- [iy83At5pbWmFg-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@aa78589: tags=[{amq.ctag-K5GhMKb-S-c0YLEe_ErjiA=springCloudBus.anonymous.rhnzSFdPSiy83At5pbWmFg}], channel=Cached Rabbit Channel: AMQChannel(amqp://guest@10.42.34.187:5672/,1), conn: Proxy@368ac624 Shared Rabbit Connection: SimpleConnection@9c497a7 [delegate=amqp://guest@10.42.34.187:5672/, localPort= 47120], acknowledgeMode=AUTO local queue size=0
29.1.2018 06:49:402018-01-29 06:49:40.732  INFO 11 --- [iy83At5pbWmFg-3] o.s.a.r.c.CachingConnectionFactory       : Created new connection: rabbitConnectionFactory#6114c045:2/SimpleConnection@2ad60f35 [delegate=amqp://guest@10.42.58.242:5672/, localPort= 41044]
29.1.2018 06:49:402018-01-29 06:49:40.736  INFO 11 --- [iy83At5pbWmFg-3] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (springCloudBus.anonymous.rhnzSFdPSiy83At5pbWmFg) durable:false, auto-delete:true, exclusive:true. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
```

The application runs in a rancher based cluster  with docker images. RabbitMQ is running in 3 instances with a two LBs (haproxy) in front. SPring is configured to use the LB using DNS round robin.

I don't understand why the rabbitMQ server fails to declare the queue that it's not able to find. It's not durable, so it should be removed automatically...

```
=ERROR REPORT==== 27-Jan-2018::19:29:31 ===
Channel error on connection <0.10043.1> (10.42.34.187:33018 -> 10.42.125.123:5672, vhost: '/', user: 'guest'), channel 373:
operation queue.declare caused a channel exception not_found: no queue 'springCloudBus.anonymous.oyO9K3MWRb-nQ2vtMxHxJQ' in vhost '/'
```

**Comment by muskanarora1** [comment]
Did anyone get the solution, as I am facing the same issue as @pcornelissen

**Comment by pcornelissen** [comment]
I have changed the cluster, so I don't use the load balancer in front of rabbitmq, this works better

**Comment by thpeng** [comment]
@chutian52 @muskanarora1 we had this issue in our project and a colleague found a solution. We tracked it to a configuration error where we set the default value for the rabbitmq property (serverside) queue_master_locator on every queue to min-masters (default is client-local). This value is quite sensible if you have high available queues (durable, mirrored) but in conjunction with the springCloudBus queues (autodelete, exlusive) it leads to these errormessages and the application will only come back after a restart, which 'resets' the queue name. See https://www.rabbitmq.com/ha.html#master-migration-data-locality and https://www.erlang-solutions.com/blog/take-control-of-your-rabbitmq-queues.html for more context. 

You can configure this behavior either globally or with RabbitMQ policies. Suppose you have naming pattern for your queues you could do the following

`{
      "vhost": "/",
      "name": "ha_queues",
      "pattern": "^<your-queue-prefix>-.*",
      "apply-to": "all",
      "definition": {
        "queue-master-locator": "min-masters",
        "ha-mode": "all"
      },
      "priority": 1
    }

{
     "vhost": "/",
     "name": "spring_cloud_bus_client_local_queues",
     "pattern": "^springCloudBus\.anonymous\..*",
     "apply-to": "all",
     "definition": {
       "queue-master-locator": "client-local"
     },
     "priority": 1
   }
`

@spencergibb is there a possibility that you might add a warning in the documentation about this behavior?
